DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS subreddit CASCADE;
DROP TABLE IF EXISTS join_sub CASCADE;
DROP TABLE IF EXISTS article CASCADE;
DROP TABLE IF EXISTS comment CASCADE;
DROP TABLE IF EXISTS save_article CASCADE;
DROP TABLE IF EXISTS vote_article CASCADE;
DROP TABLE IF EXISTS vote_comment CASCADE;